"""empty message

Revision ID: 63b77aebd74c
Revises: 78c40282315d
Create Date: 2021-09-09 16:44:54.671110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b77aebd74c'
down_revision = '78c40282315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gotos', sa.Column('loc_name', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gotos', 'loc_name')
    # ### end Alembic commands ###
