"""empty message

Revision ID: 69b8df578c59
Revises:
Create Date: 2021-07-30 15:28:36.112594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b8df578c59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('api_id', sa.String(length=100),
                              unique=True, nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('image_url', sa.String(
                        length=1000), nullable=True),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=40), nullable=False),
                    sa.Column('avatar', sa.String(length=3000), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('feeds',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('loc_id', sa.String(length=100), nullable=True),
                    sa.Column('body', sa.String(length=500), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['loc_id'], ['locations.api_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reviews',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('review', sa.String(length=300), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('loc_id', sa.String(length=100), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['loc_id'], ['locations.api_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('traveled',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('location_id', sa.String(
                        length=100), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['location_id'], ['locations.api_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'location_id')
                    )
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('feed_id', sa.Integer(), nullable=True),
                    sa.Column('comment', sa.String(length=300), nullable=True),
                    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('traveled')
    op.drop_table('reviews')
    op.drop_table('feeds')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
