"""empty message

Revision ID: 78c40282315d
Revises: 911331fbf9bf
Create Date: 2021-09-07 15:26:52.917477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c40282315d'
down_revision = '911331fbf9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gotos', sa.Column('venue_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gotos', 'venue_name')
    # ### end Alembic commands ###
