"""empty message

Revision ID: 95d01641e886
Revises: 69b8df578c59
Create Date: 2021-08-02 16:57:49.236533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d01641e886'
down_revision = '69b8df578c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('feeds', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('feeds', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'feeds', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.drop_column('feeds', 'updated_at')
    op.drop_column('feeds', 'created_at')
    op.drop_column('feeds', 'user_id')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
