"""empty message

Revision ID: e91e8940fe6a
Revises: 95d01641e886
Create Date: 2021-08-07 20:10:42.229591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91e8940fe6a'
down_revision = '95d01641e886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('loc_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'comments', 'locations', ['loc_id'], ['api_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'loc_id')
    # ### end Alembic commands ###
